In [1]:
import numpy as np

# Create arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,5.5)

array([5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5])

In [7]:
a = np.array([1,2,3,4,5,6,12])
a

array([ 1,  2,  3,  4,  5,  6, 12])

In [10]:
a[2] = 10 #indexing starts with 0

In [11]:
a

array([ 1,  2, 10,  4,  5,  6, 12])

In [13]:
np.arange(10) #exclusive default 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,100,11) # figures out how to fill the in-between elements

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [18]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional arrays

In [21]:
np.zeros((5,2)) # need to add parentheses

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
        [1,2,3],
        [4,5,6],
        [7,8,9]
])

In [25]:
n[0,1]

2

In [26]:
n[0]

array([1, 2, 3])

In [31]:
n[:,1 ] # row operator to get a column

array([2, 5, 8])

In [36]:
np.random.seed(2)   # pseudo-random if we use the same seed then we get the same numbers
np.random.rand(5,2) # uniform distribution, numbers between 0,1

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [38]:
np.random.seed(2)
np.random.randn(5,2) # get from normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [40]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operators

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
a + 1 # for a list we would need a loop, in numpy its ez

array([1, 2, 3, 4, 5])

In [44]:
a * 2

array([0, 2, 4, 6, 8])

In [45]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [47]:
b = (10 + (a * 2)) ** 2 # expressions are also allowed

In [49]:
a + b # also between arrays

array([100, 145, 198, 259, 328])

In [50]:
a * b

array([   0,  144,  392,  768, 1296])

In [52]:
a / b + 10

array([10.        , 10.00694444, 10.01020408, 10.01171875, 10.01234568])

# Comparison operations

In [54]:
a >= 2

array([False, False,  True,  True,  True])

In [58]:
b= b/100

In [59]:
a > b

array([False, False,  True,  True,  True])

In [60]:
a[a > b] # return elements in a for which the condition is true

array([2, 3, 4])

# Summarizing Operations 

Instead of returning another array they return a single number

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.sum()

10

In [63]:
a.mean()

2.0

In [64]:
a.std()

1.4142135623730951

In [69]:
n.std() # also for 2-D

2.581988897471611

In [70]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
n.min(axis = 1)

array([1, 4, 7])

In [72]:
n.min(axis = 0)

array([1, 2, 3])