In [9]:
import numpy as np

# Vector operations

In [13]:
u = np.array([1,2,3,4])
v = np.array([0,0,1,4])

In [14]:
def vector_vector_multiplication(u, v): 
    # dot product
    assert u.shape[0] == v.shape[0] # same dimensions
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i]*v[i]
        
    return result

In [15]:
vector_vector_multiplication(u, v)

19.0

In [16]:
u.dot(v) # for vector multiplication built-in

19

## Matrix vector multiplication 

In [34]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

v = np.array([1, 0.5, 2, 1])

U.shape

(3, 4)

In [35]:
def matrix_vector_multiplication(U,v):
    
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0] 
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [36]:
matrix_vector_multiplication(U,v)

array([20. ,  6. ,  8.5])

In [37]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [39]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [44]:
def matrix_matrix_multiplication(U, V):
    
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        
        vi = V[:, i]
        
        Uvi = matrix_vector_multiplication(U, vi)
        
        result[:, i] = Uvi
        
    return result

In [45]:
matrix_matrix_multiplication (U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [46]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [47]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
I = np.eye(3)

In [49]:
V.dot(I) # I can only be 3x3 or same rows with V columns

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [50]:
Vs = V[[0, 1, 2]] # first three rows of V
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [53]:
Vs_inv = np.linalg.inv(Vs)

In [54]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])